### ISSUE TITLE
Gateway Timeout

### ISSUE THREAD

**Issue by bendwyer** [gregoryseibert/funkwhale-docker-traefik#1]
Thanks for sharing your setup. It's gotten me really close to having everything working.

I have a Traefik container already setup, so I'm trying to integrate Funkwhale with that.  I can deploy all the containers and they spin up with no errors, but when I go to actually load the login page for Funkwhale I'm hit with a `Gateway Timeout`. (The Let's Encrypt certificate is being setup though. I can view the certificate for the page (it's loading in HTTPS) and it's correct for my URL.)

My Traefik container is working for all my other deployed containers, so all I can figure is something between NGINX and Traefik isn't playing nice.

I've included the relevant config files below; please let me know if you need any others from me.

funkwhale - `docker-compose.yml`
```
version: '3'

services:

  postgres:
    restart: unless-stopped
    env_file: .env
    image: postgres:9.4
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  redis:
    restart: unless-stopped
    env_file: .env
    image: redis:3
    volumes:
      - ./data/redis:/data

  celeryworker:
    restart: unless-stopped
    image: funkwhale/funkwhale:${FUNKWHALE_VERSION:-latest}
    env_file: .env
    command: celery -A funkwhale_api.taskapp worker -l INFO
    links:
      - postgres
      - redis
    environment:
      - C_FORCE_ROOT=true
    volumes:
      - "${MUSIC_DIRECTORY_SERVE_PATH-/srv/funkwhale/data/music}:${MUSIC_DIRECTORY_PATH-/music}:ro"
      - "${MEDIA_ROOT}:${MEDIA_ROOT}"

  celerybeat:
    restart: unless-stopped
    image: funkwhale/funkwhale:${FUNKWHALE_VERSION:-latest}
    env_file: .env
    command: celery -A funkwhale_api.taskapp beat -l INFO
    links:
      - postgres
      - redis

  api:
    restart: unless-stopped
    image: funkwhale/funkwhale:${FUNKWHALE_VERSION:-latest}
    env_file: .env
    container_name: funkwhale-api
    volumes:
      - "${MUSIC_DIRECTORY_SERVE_PATH-/srv/funkwhale/data/music}:${MUSIC_DIRECTORY_PATH-/music}:ro"
      - "${MEDIA_ROOT}:${MEDIA_ROOT}"
      - "${STATIC_ROOT}:${STATIC_ROOT}"
      - ./front/dist:/frontend
    ports:
      - "${FUNKWHALE_API_IP:-127.0.0.1}:${FUNKWHALE_API_PORT:-5000}:5000"
    links:
      - postgres
      - redis

  frontend:
    image: nginx:1.15.2-alpine
    restart: always
    privileged: true
    container_name: funkwhale-frontend
    volumes:
      - ./html:/var/www/html
      - ./custom:/srv/funkwhale/custom
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/funkwhale_proxy.conf:/etc/nginx/funkwhale_proxy.conf
      - ./data/media:/srv/funkwhale/data/media
      - ./data/static:/srv/funkwhale/data/static
      - ./data/music:/srv/funkwhale/data/music:ro
    labels:
      - "traefik.enable=true"
      - "traefik.backend=funkwhale.domain.com"
      - "traefik.frontend.rule=Host:funkwhale.domain.com"
      - "traefik.docker.network=proxy"
      - "traefik.port=80"
    ports:
      - 8881:80
    expose:
      - "8080"
```

funkwhale - `nginx.conf`
```
user root;

events {
    worker_connections 1024; # increase if you have lots of clients
    accept_mutex off; # "on" if nginx worker_processes > 1
}

http {
    include mime.types;

    # fallback in case we can't determine a type
    default_type application/octet-stream;
    sendfile on;

    # Update this with the IP to your funkwhale API...
    upstream funkwhale-api {
        server funkwhale_api_1:5000;
    }

    # required for websocket support
    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }

    server {
        listen 80 default_server;
        root /var/www/html;

        server_name funkwhale.domain.com;

        location = / {
            return 301 /library;
        }

        location / {

            sub_filter '</head>' '<link href=/custom/custom.css rel=stylesheet></head>';
            sub_filter_once on;

            try_files $uri $uri/ @rewrites;
        }
        location @rewrites {
            rewrite ^(.+)$ /index.html last;
        }
        location /api/ {
            include /etc/nginx/funkwhale_proxy.conf;

            # this is needed if you have file import via upload enabled
            client_max_body_size 30M;
            proxy_pass   http://funkwhale-api/api/;
        }
        location /federation/ {
            include /etc/nginx/funkwhale_proxy.conf;
            proxy_pass   http://funkwhale-api/federation/;
        }
        # You can comment this if you do not plan to use the Subsonic API
        location /rest/ {
            include /etc/nginx/funkwhale_proxy.conf;
            proxy_pass   http://funkwhale-api/api/subsonic/rest/;
        }
        location /.well-known/ {
            include /etc/nginx/funkwhale_proxy.conf;
            proxy_pass   http://funkwhale-api/.well-known/;
        }
        location /media/ {
            alias /srv/funkwhale/data/media/;
        }
        location /_protected/media {
            # this is an internal location that is used to serve
            # audio files once correct permission / authentication
            # has been checked on API side
            internal;
            alias   /srv/funkwhale/data/media;
        }
        location /_protected/music {
            # this is an internal location that is used to serve
            # audio files once correct permission / authentication
            # has been checked on API side
            # Set this to the same value as your MUSIC_DIRECTORY_PATH setting
            internal;
            alias   /srv/funkwhale/data/music;
        }
        location /staticfiles/ {
            # django static files
            alias /srv/funkwhale/data/static/;
        }
        location /settings.json {
            alias /srv/funkwhale/custom/settings.json;
        }
        location /custom {
            alias /srv/funkwhale/custom;
        }
    }

}
```

**Comment by gregoryseibert** [comment]
Yeah I had a small mistake in the docker-compose file for the funkwhale-frontend.
Would you please ty out replacing the volume line `- ./html:/var/www/html` with `- ./front/dist:/var/www/html`?

**Comment by bendwyer** [comment]
I made the change and redeployed everything from scratch, but I'm still getting the same issue. Interestingly the `funkwhale-frontend` logs did pop up a few errors, but it's only when I navigate to `music.domain.com:8881`. Otherwise it's the same old `Gateway Timeout`.

```

[IP ADDRESS] - - [22/Aug/2018:09:10:50 +0000] "GET / HTTP/1.1" 301 185 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36"


[IP ADDRESS] - - [22/Aug/2018:09:11:40 +0000] "\x16\x03\x01\x02\x00\x01\x00\x01\xFC\x03\x038\x87\xC9\xE5\x85\x16D\xCA jz2F\xFD?*@\xBF\xAD\x12dx\xBA\xCCY\x01\xF0\x1EW\xE9\xC0\x91 \xA0\x02tD\x95\xD2\xD0\xEC\x17\xACk\x858\x8B\xAE\x1E\x81\xDB\x068\xD5p\xCA\x15\x91Kx\xFAT\xDA\x85\x9B\x00\x22zz\x13\x01\x13\x02\x13\x03\xC0+\xC0/\xC0,\xC00\xCC\xA9\xCC\xA8\xC0\x13\xC0\x14\x00\x9C\x00\x9D\x00/\x005\x00" 400 173 "-" "-"


[IP ADDRESS] - - [22/Aug/2018:09:11:41 +0000] "\x16\x03\x01\x00\xCD\x01\x00\x00\xC9\x03\x03\x1D\x0F\xED\x0E\xA3\x850\xE0*\xBC\x9Fi\xC0^\xBCk\x95\x82\x97\x14\x8CK\x9F\xB6\xAF\xAD\x8F\xBA\x22\xAE\x92\xDB\x00\x00\x1Czz\xC0+\xC0/\xC0,\xC00\xCC\xA9\xCC\xA8\xC0\x13\xC0\x14\x00\x9C\x00\x9D\x00/\x005\x00" 400 173 "-" "-"
```

**Comment by gregoryseibert** [comment]
This error log seems really strange.
Is your funkwhale-frontend container in the same network as traefik?

**Comment by bendwyer** [comment]
It is not, they're deployed on different networks.

traefik: `traefik_default`
funkwhale: `funkwhale_default` (all funkwhale containers, including funkwhale-frontend)

1) Should I move the `funkwhale-frontend` container to the `traefik_default` network? 
2) Should `funkwhale-frontend` also stay connected to the `funkwhale_default` network?

**Comment by gregoryseibert** [comment]
The funkwhale-frontend has to be in the same network as traefik, as well as other containers, which should be reverse proxied with traefik.
And the funkwhale-frontend also has to be in the same network with at least the funkwhale api.
But I have all funkwhale containers in the same network, just in case.

Try adding this code at the end of your docker-compose.yml for funkwhale:

```
networks:
  internal:
  traefik_default:
    external: true
```

And then for your funkwhale-frontend:

```
  networks:
    - internal
    - traefik_default
```

And for the other funkwhale containers:

```
  networks:
    - internal
```

I didn't test, if this works for default networks created by docker-compose, but it should work.
